# Generated by Django 3.1.5 on 2021-03-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetProfileDonate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Email', models.EmailField(max_length=250)),
                ('Phone', models.CharField(max_length=30)),
                ('Contry', models.CharField(max_length=100)),
                ('TypeBlood', models.CharField(max_length=3)),
            ],
        ),
    ]
