# Generated by Django 3.1.5 on 2021-03-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getprofiledonate',
            old_name='Contry',
            new_name='Country',
        ),
        migrations.AlterField(
            model_name='getprofiledonate',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
