# Generated by Django 3.1.5 on 2021-04-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=250)),
                ('Phone', models.CharField(max_length=30)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
